### ISSUE TITLE
Dry-run Task 1

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra#4]
The Task 1 workflow has been merged into `main`, so now we are ready to start dry-running.  If you haven't yet:

**On Synapse:**
- [x] From live, create an Evaluation Queue for Task 1 - make note of its evaluation ID.
- [x] From staging, upload a new file and link it to this repo.  You will use the URL that will download this repo as a ZIP file; this is done by clicking on **Code** button on the [main page](https://github.com/Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra) > right-clicking **Download Zip** > **Copy Link Address**. Save the "file" (technically a link) - make note of its synID.
- [x] Once saved, add an annotation to the file called `ROOT_TEMPLATE`.  Its value should follow this naming format: 
   ```
   {name of repo}-{branch}/{workflow file to run}
   ```
   So in this case:
   ```
   RARE-X-DREAM-Challenge-Infra-main/task1_workflow.cwl
   ```
   This annotation will help the orchestrator identify which CWL file among the downloaded repo it will run.

**On the instance:**
- [x] (if needed) stop the orchestrator with `docker-compose down`
- [x] Enter the `.env` file and edit `EVALUATION_TEMPLATES` to include the Task 1 workflow.  It should look something like this:
   ```
   EVALUATION_TEMPLATES={"<evaluation id>": "<workflow synID>"}
   ```
- [x] Update other properties among the `.env` file as needed. 
    - [x] I recommend adding `MAX_CONCURRENT_WORKFLOWS` (which isn't included in the `.envTemplate` for reason), which specifies how many concurrent submissions the orchestrator will run at a time - 10 is the default, which may be too high. It will be ideal to only run as many submissions that the instance can handle, e.g. if the instance only has 32GB memory available and we are allowing 10GB of memory for each container (determined by the [run_docker script](https://github.com/Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra/blob/b23ee73603a4d598ae682b6bc038b9c189aa4dcc/scripts/run_docker.py#L161)), then we should reduce the number of concurrent submissions to 2 or 3.
- [x] restart the orchestrator with `docker-compose up -d`

Once you're done, we can start submitting dummy submissions to the queue.  Some suggested test cases are:

**Test Case** | **Expected Result** | **Reason**
--|--|--
[RARE-X Challenge site](https://www.synapse.org/rarex) | INVALID | Synapse project should not be the challenge site
[Awesome Writeup]() | VALIDATED | Synapse project is accessible to the Organizers team (since it's publicly available)
Some private Synapse project | INVALID | Synapse project is not accessible to the Organizers team
Some private Synapse project that is shared with "RARE-X Organizers" team | VALIDATED | Synapse project is accessible to the Organizers team
Some Docker image | INVALID | Submission should not be a Docker model
Some file | INVALID | Submission should not be a file

Feel free to try out any other test cases too!

CC: @chepyle

**Comment by mdsage1** [comment]
Performed tests using the following:

**Test Case** | **Expected Result** | **Reason** | **Actual Result**
--|--|--|--
[RARE-X Challenge site](https://www.synapse.org/rarex) | INVALID | Synapse project should not be the challenge site
[Awesome Writeup]() | VALIDATED | Synapse project is accessible to the Organizers team (since it's publicly available) | **This links to the Dry Run GitHub Issue** @vpchung 
Some private Synapse project | INVALID | Synapse project is not accessible to the Organizers team
Some private Synapse project that is shared with "RARE-X Organizers" team | VALIDATED | Synapse project is accessible to the Organizers team
Task2 Model Docker image | INVALID | Submission should not be a Docker model | Docker Digest is Required.
Orca Test Project/TestFile.txt | INVALID | Submission should not be a file | TBD. Thank you for your submission!

**Comment by vpchung** [comment]
> This links to the Dry Run GitHub Issue

Oh sorry, I must've forgotten to add a link. Here it is: https://www.synapse.org/awesome_writeup

**Comment by mdsage1** [comment]
@vpchung Every test result was as expected but Awesome_Challenge. It says that the project needs to be shared w/Rare-X Organizers. I cannot change the project share settings for that one.

**Comment by vpchung** [comment]
Thanks, @mdsage1 !

> It says that the project needs to be shared w/Rare-X Organizers.

Gahh, yeah, that's a bug I recently come across as well.  It's failing because the project is not directly shared with the specified team, despite being publicly available.
