### ISSUE TITLE
Dry-run Task 2

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra#5]
Similar to #4 , let's start dry-running Task 2.  The following steps will be similar to #4, so head there for more context if needed.

**On Synapse:**
- [x] From live, create an Evaluation Queue for Task 2 - make note of its evaluation ID.
- [x] From staging, upload a new file and link it to this repo - make note of its synID.
- [x] Add the annotation, `ROOT_TEMPLATE`, but this time using the value:
   ```
   RARE-X-DREAM-Challenge-Infra-main/task2_workflow.cwl
   ```

**On the instance:**
- [x] (if needed) stop the orchestrator with `docker-compose down`
- [x] Add the Task 2 workflow to `EVALUATION_TEMPLATES` in the `.env` file
- [x] If you haven't yet, add `MAX_CONCURRENT_WORKFLOWS` to `.env` (which isn't included in the `.envTemplate` for reason), to specify the number of concurrent submissions the orchestrator will run at a time (10 is the default, which could be too high).
- [x] restart the orchestrator with `docker-compose up -d`

In addition to the infra configurations, we will also need to containerize Jake's baseline model so that we will have something to submit.  This baseline model can be something we share with the participants, so let's push the image up to live instead of staging.

CC: @chepyle

**Comment by mdsage1** [comment]
@vpchung Do I add a link to the repo again if it is already there or can I just add another annotation to the ROOT_TEMPLATE key value pair?
![image](https://github.com/Sage-Bionetworks-Challenges/RARE-X-DREAM-Challenge-Infra/assets/122999770/b8a2001f-57d7-4daf-9ad7-1279c3a2023d)

**Comment by vpchung** [comment]
@mdsage1 great question!  You will need to upload the file again because the orchestrator uses that annotation value to determine which file within the repo to run.  If there are multiple values, the orchestrator will not be able to determine what the workflow file is.

**Comment by mdsage1** [comment]
MAX_CONCURRENT_WORKFLOWS is set to 2

Performed tests using the following:

**Test Case** | **Expected Result** | **Reason** | **Actual Result**
--|--|--|--
[RARE-X Challenge site](https://www.synapse.org/rarex) | INVALID | Submission should not be the challenge site |
[Awesome Writeup](https://www.synapse.org/#!Synapse:syn36025126/wiki/619033) | INVALID | Submission should not be a Synapse project. | 
Some private Synapse project. Used w/Awesome_Writeup while it hadn't been shared w/RARE-X Organizers | INVALID | Synapse project is not a Docker model. |
Some private Synapse project that is shared with "RARE-X Organizers" team.  | INVALID | Synapse project is accessible to the Organizers team but not a Docker model. |
Task2 Model Docker image | VALIDATED | Submission should be a Docker model |
Orca Test Project/TestFile.txt | INVALID | Submission should not be a file |
